### ISSUE TITLE
I met this error when run main.py.

### ISSUE THREAD

**Issue by bemoregt** [rohithreddy024/Visual-Attention-Pytorch#1]
Hi, @rohithreddy024 

I met this error when run main.py.

tezro@tezro:~/Deep07/Visual-Attention-Pytorch$ python3 main.py 
Namespace(batch_size=32, epochs=101, k=2, lr=0.0001, n_c=120, n_glimpses=1, n_jobs=4, n_samples=20, num_workers=4, resume_training=False, rnn_hidden=2048, start_size=2, std_dev=0.2, task='train', valid_size=0.3)
/home/tezro/.local/lib/python3.8/site-packages/torch/nn/functional.py:1628: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "main.py", line 278, in <module>
    training()
  File "main.py", line 187, in training
    la, lb, lr = train_model(x_batch, labels, info)
  File "main.py", line 121, in train_model
    _, _, _, _, output = my_model(l, hc1, cv, info, last = True)
  File "/home/tezro/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tezro/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/tezro/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/tezro/.local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/tezro/.local/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/tezro/.local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/tezro/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tezro/Deep07/Visual-Attention-Pytorch/models.py", line 166, in forward
    g = self.glimpse(l_prev, info)  #Extract glimpse based on tuple
  File "/home/tezro/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tezro/Deep07/Visual-Attention-Pytorch/models.py", line 68, in forward
    phi = retina(l_prev, info, self.opt, self.training) #Extracts high, medium and low resolution patches corresponding to a location centre; Also compressed to 96x96 size
  File "/home/tezro/Deep07/Visual-Attention-Pytorch/helper_functions.py", line 64, in retina
    phi.append(extract_patches_batch(l, size))
  File "/home/tezro/Deep07/Visual-Attention-Pytorch/helper_functions.py", line 54, in extract_patches_batch
    patches = Parallel(n_jobs=opt.n_jobs, backend="threading")(
  File "/home/tezro/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/home/tezro/.local/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/tezro/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/tezro/.local/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/tezro/.local/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/tezro/Deep07/Visual-Attention-Pytorch/helper_functions.py", line 34, in get_patch
    img, imgsize = get_image(opt, info[i], istrain) #Get context image
  File "/home/tezro/Deep07/Visual-Attention-Pytorch/helper_functions.py", line 23, in get_image
    img = img.crop((from_w, from_h, from_w + size, from_h + size))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 1128, in crop
    return self._new(self._crop(self.im, box))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 1142, in _crop
    x0, y0, x1, y1 = map(int, map(round, box))
TypeError: type Tensor doesn't define __round__ method

What's wrong to me?

Thanks.

@bemoregt.

**Comment by fatalfeel** [comment]
use my patch
https://www.mediafire.com/file/kl7epkvxrg1641n/Visual-Attention-Pytorch.tar.xz
